[build-system]
requires = [
    "setuptools             >= 64, < 100", # builer for python packages 
    "setuptools_scm[toml]   >= 8,     < 50"  # pluging for getting the version from github
    ]
build-backend = "setuptools.build_meta"

[project]
name = "HiDimStat"
dynamic = ["version"]  # dynamical version extracted from the git version
authors = [  # TODO see if we need more details
    { name = "HiDimStat developers" }  # possibility to add an email address
    ]
maintainers = [
    { name = "Bertrand Thirion", email = "bertrand.thirion@inria.fr" },
]
# Don't forget to have the coherence between the README and the description
description = "High-dimensional statistical inference tools for Python"
keywords = ["statistic", "high dimension", "importance variable"]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3:: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development",
    "Topic :: Scientific/Engineering",
]
requires-python = ">=3.9, < 4"
dependencies = [
    "joblib       >= 1.2.0, < 2",
    "numpy        >= 1.25,  < 3",
    "pandas       >= 2.0,   < 3",
    "scikit-learn >= 1.4,   < 2",
    "scipy        >= 1.6,   < 2",
]

[project.optional-dependencies]
# Requirements necessary for building the documentation
doc = [
    "memory_profiler        >= 0.61.0",
    "mne                    >= 1.7.1",
    "nilearn                >= 0.10.4",
    "numpydoc               >= 1.7.0",
    "pillow                 >= 10.4.0",
    "PyQt5                  >= 5.15.10",
    "pyvista                >= 0.44.0",
    "pyvistaqt              >= 0.11.1",
    "pydata_sphinx_theme    >= 0.16.1",
    "sphinxcontrib-bibtex   >= 2.6.2",
    "sphinx-gallery         >= 0.16.0",
    "seaborn",
]
plotting = [
    "matplotlib>=3.9.0",
]
style = [
    "black  >= 24.4.2", 
    "isort  >= 5.13.2"
]
# For running unit and docstring tests
test = [
    "iniconfig  >= 0.1,  < 3",
    "packaging  >= 14.0, < 100",
    "coverage   >= 6.0,  < 8",
    "pytest     >= 8.0,  < 9",
    "pytest-cov >= 3.0,  < 7",
]

[project.urls]
Repository = "https://github.com/mind-inria/hidimstat"
Documentation = "https://github.com/hidimstat/hidimstat.github.io"
Teams = "https://team.inria.fr/mind/"
Issues = "https://github.com/mind-inria/hidimstat/issues"
Discussion = "https://github.com/mind-inria/hidimstat/discussions" # TODO see if we keep it or not

# Configuration of the builder 
[tool.setuptools]
package-dir = {"" = "src"} # define the root of the packages as src

# file where the version is save
[tool.setuptools_scm]
version_file = "src/hidimstat/_version.py"

[tool.pytest.ini_options]
testpaths = "tests"
