# This workflow is for getting the information require for the decision in the main workflow.

name: Information

on:
  # Allows you to run this workflow from another workflow
  workflow_call:
    inputs:
      commit_event_sha:
        required: true
        type: string
      commit_PR_sha:
        required: true
        type: string

# disable all the permission for the workflow
permissions: {}

jobs:
    get_head_commit_message:
        name: Get Head Commit Message
        runs-on: ubuntu-latest
        outputs:
          COMMIT_MSG: ${{ steps.get_commit_message.outputs.COMMIT_MSG }}
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
            with:
              ref: ${{ inputs.commit_PR_sha }}
    
          - name: Get commit message
            id: get_commit_message
            run: |
              echo "COMMIT_MSG=$(git log -1 --pretty=%B ${{  inputs.commit_event_sha }})"
              echo "${{ inputs.commit_PR_sha }}"
              echo "COMMIT_MSG=$(git log -1 --pretty=%B ${{ inputs.commit_event_sha }})" >> $GITHUB_OUTPUT
    