# For more information see: https://black.readthedocs.io/en/stable/integrations/github_actions.html
name: Lint

on: 
  workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
