name: Documentation

on:
  # Allows you to run this workflow from another workflow
  workflow_call:

env:
    # Force to use color
    FORCE_COLOR: true
    BROWSER: /usr/bin/firefox
    DISPLAY: :99.0

# disable all the permission for the workflow
permissions: {}

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install -e .
          python -m pip install .[doc,plotting]
      - name: Sphinx build
        id: build-docs
        run: |
          sphinx-build -b html doc_conf doc/_build/html
      - name: Upload documentation
        if: steps.build-docs.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: DocHTML
          path: doc/_build/html
          
