name: 'CI'
on:
  workflow_call:
    
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: True
        matrix:
          python-version: ["3.12"]
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install the dependance
          run: |
            python -m pip install --upgrade pip
            python -m pip install .[test]
        - name: Generate coverage report
          run: |
            python -m pytest --doctest-modules --junitxml=jest-junit.xml --cov=com --cov-report=xml --cov-report=html 
        - name: Upload pytest test results
          uses: actions/upload-artifact@v4
          with:
            name: test-results
            path: jest-junit.xml
          # Use always() to always run this step to publish test results when there are test failures
          if: success() || failure()        # run this step even if previous step failed