# Management of the action do made during a pull request

name: 'Main_workflow'
on:
  pull_request:
    branches: main
  # allows to push on branches
  push:
    branches: main

# disable all the permission for the workflow
permissions: {}

# Cancel existing runs 
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get_information:
    name: Get Information
    uses: ./.github/workflows/call_get_info.yml

  linter:
    name: Linter
    needs: [get_information]
    uses: ./.github/workflows/call_black.yml
  
  tests:
    name: tests
    needs: [linter, get_information]
    if: ${{ !contains(needs.get_information.outputs.COMMIT_MSG, '[skip tests]') }}
    uses: ./.github/workflows/call_test_package.yml
  
  no_tests:
    name: no_tests
    needs: [linter, get_information]
    if: ${{ contains(needs.get_information.outputs.COMMIT_MSG, '[skip tests]') }}
    uses: ./.github/workflows/call_no_test.yml
  
  tests_publish:
    name: tests_publish
    needs: [tests, no_tests, get_information]
    if: |
      (needs.tests.result != 'cancelled'
      && needs.no_tests.result != 'cancelled'
      && github.event.pull_request.draft == false)
      || contains(needs.get_information.outputs.COMMIT_MSG, '[doc ')
    permissions:
      pull-requests: write
    uses: ./.github/workflows/call_publish_result.yml

  # debugger:
  #   needs: linter 
  #   env: 
  #     STATE_LINTER: ${{ needs.linter.result }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: print output
  #       run: 
  #         echo "Linter "$STATE_LINTER
  #   if: ${{ always() }} 
    