# Management of the action do made during a pull request

name: 'Main_workflow'
on:
  pull_request:
    branches: main
  push:
    branches: main

# disable all the permission for the workflow
permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

# Cancel existing runs 
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linter:
    name: Linter
    uses: ./.github/workflows/call_black.yml
  
  tests:
    name: tests
    needs: [linter]
    uses: ./.github/workflows/call_test_package.yml
  
  tests_publish:
    name: tests_publish
    needs: [tests]
    if: ${{ always() }}
    permissions:
      contents: write
    uses: ./.github/workflows/call_test_package.yml

  make_documentation:
    name: Make_documentation
    needs: [linter, tests]
    uses: ./.github/workflows/call_build_docs.yml

  # debugger:
  #   needs: linter 
  #   env: 
  #     STATE_LINTER: ${{ needs.linter.result }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: print output
  #       run: 
  #         echo "Linter "$STATE_LINTER
  #   if: ${{ always() }} 
    